-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;

CREATE TABLE category (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
category_name TEXT NOT NULL
);

CREATE TABLE product (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
product_name TEXT NOT NULL,
price DECIMAL NOT NULL 


);